### ISSUE TITLE
Create an edge-tag

### ISSUE THREAD

**Issue by jwanglof** [Docker-Hub-frolvlad/docker-alpine-python2#1]
Hey! Thanks for this base-image, saves me some trouble =)
I was just wondering if you can add an edge-tag for the image as well as latest?
Thanks!

**Comment by frol** [comment]
Hmm, that is actually a good idea. I will push edge images tomorrow.

**Comment by frol** [comment]
I'm sorry, I was too busy today to do this. What is your use-case for having `edge` image as a base? You can always add edge repo on the next layer to use experimental packages without any restrictions.

**Comment by jwanglof** [comment]
No worries =)
I need `edge` because `py-psycopg2` doesn't exist in the community/main-repo and I couldn't add the `edge`-repo for some reason

**Comment by frol** [comment]
```
/ # apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/main --no-cache py-psycopg2
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/3) Installing py-egenix-mx-base (3.2.9-r0)
(2/3) Installing libpq (9.5.2-r1)
(3/3) Installing py-psycopg2 (2.6.1-r0)
OK: 61 MiB in 24 packages
```

Everything seems to be fine. You can also install `psycopg2` via pip: https://github.com/frol/docker-alpine-python3/issues/1

**Comment by jwanglof** [comment]
Strange, guess it failed to add the repo or something. I'll close this issue since it can be fixed with the current version =)
Thanks for looking into it!
